version: "3"

services:
  # PostgreSQL
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env

  # API (Development)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev:docker
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/src
      - nodemodules:/src/node_modules
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
  nodemodules: {}
