version: "3"

services:
  # PostgreSQL
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ollo
      POSTGRES_PASSWORD: ollo_password
      POSTGRES_DB: ollo_li
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres-data:
