@base_url = http://localhost:3000
@base_pos_url = api
@host_name = {{base_url}}/{{base_pos_url}}
@jwt_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZlMjJmYmE4LTc4NmEtNDg5Yy04NzM2LTNhMDFhZDk5NzkxNCIsImlhdCI6MTcxMDc5Nzk4MywiZXhwIjoxNzEwODAxNTgzfQ.R9CBiSyyKLj3H6h3Cv4OLsW07y6KQhCP-qdOARZ2Zy4
@content_type = application/json

# Some params
@user_email = romuloassis.as@gmail.com
@user_name = Jhon Doe
@user_password = asd)Aasdas_000


### GET - Chek API is UP
GET {{base_url}}/healthcheck HTTP/1.1
Content-Type: {{content_type}}

### POST - Create a new user
POST {{host_name}}/users HTTP/1.1
Content-Type: {{content_type}}

{
  "email": "{{user_email}}",
  "name": "{{user_name}}",
  "password": "{{user_password}}"
}

### POST - Recover Password (THIS ROUT NOT EXISTS)
POST {{host_name}}/user/recoveryPassword HTTP/1.1
Content-Type: {{content_type}}

{
  "email": "{{user_email}}",
}

### POST - Email Verify
@email_unique_key=38fee699-7067-4f57-999a-243771190366
POST {{host_name}}/email/verify/{{email_unique_key}} HTTP/1.1
Content-Type: {{content_type}}

{
  "email": "{{user_email}}"
}

### POST - Email resend code
POST {{host_name}}/email/resendVerificationEmail HTTP/1.1
Content-Type: {{content_type}}

{
  "email": "{{user_email}}"
}

### POST - Login
POST {{host_name}}/auth HTTP/1.1
Content-Type: {{content_type}}

{
  "email": "{{user_email}}",
  "password": "{{user_password}}"
}

### POST - Shortener a link
POST {{host_name}}/links/shortener HTTP/1.1
Content-Type: {{content_type}}
Authorization: bearer {{jwt_token}}

 {
  //"url": "https://any_site/lllll",
  "alias": "MySite52",
   "validAt": "2025-01-16T19:52:21.208Z",
   "metadata": {
     "title": "my site",
     "description": "just a site",
     "image": "https://robohash.org/UTI.png?set=set1"
   }
 }

### PUT - Update a link
PUT {{host_name}}/links/783d7c98-e32a-462e-b4f3-0e55621403a4 HTTP/1.1
Content-Type: {{content_type}}
Authorization: bearer {{jwt_token}}

 {
  "redirectTo": "https://any_site/kk",
  "hash": "06e4588d",
  "alias": "MySite5",
  "validAt": "2024-01-27T12:30:24.958Z",
  "active": false
 }

### GET - Get All links
GET {{host_name}}/links HTTP/1.1
Content-Type: {{content_type}}
Authorization: bearer {{jwt_token}}

