name: Main Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  NODE_VERSION: "20"

jobs:
  InstallDeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: ~/.npm
          key: |
            ${{ runner.os }}-npm-v3-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm install

  CodeAnalysis:
    runs-on: ubuntu-latesta
    needs: [InstallDeps]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: |
            ${{ runner.os }}-npm-v3-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Audit vulnerability
        continue-on-error: true
        id: npm_audit
        run: |
          AUDIT_OUTPUT=$(npm audit --audit-level moderate)
          echo "audit_output=$AUDIT_OUTPUT" >> $GITHUB_OUTPUT

      - name: Display Alert Message for npm audit failure
        if: ${{ steps.npm_audit.outputs.audit_output != '' }}
        continue-on-error: true
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## 🚨 Result of `npm audit`
            ```
            ${{steps.npm_audit.outputs.audit_output}}
            ```
          mode: recreate
          comment_tag: audit

      - name: Lint
        run: npm run lint --fix

  Tests:
    runs-on: ubuntu-latest
    needs: [InstallDeps, CodeAnalysis]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: |
            ${{ runner.os }}-npm-v3-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Run test
        run: npm run test:ci

  Coverage:
    runs-on: ubuntu-latest
    needs: [Tests]
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
