name: Main Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  InstallDeps:
    uses: olloapp/pipelines/templates/install-deps.yml@main

  CodeAnalysis:
    uses: olloapp/pipelines/templates/code-analysis.yml@main
    needs: [InstallDeps]

  Tests:
    uses: olloapp/pipelines/templates/tests.yml@main
    needs: [InstallDeps, CodeAnalysis]
