name: Main Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  InstallDeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: node_Modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm ci

  CodeAnalysis:
    runs-on: ubuntu-latest
    needs: [InstallDeps]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('package-lock.json') }}

      - name: Audit vulnerability
        continue-on-error: true
        id: npm_audit
        run: |
          AUDIT_OUTPUT=$(npm audit --audit-level moderate)
          echo "audit_output=$AUDIT_OUTPUT" >> $GITHUB_OUTPUT

      - name: Display Alert Message for npm audit failure
        if: ${{ steps.npm_audit.outputs.audit_output != '' }}
        continue-on-error: true
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## 🚨 Result of `npm audit`
            ```
            ${{steps.npm_audit.outputs.audit_output}}
            ```
          mode: recreate
          comment_tag: audit

      - name: Lint
        continue-on-error: true
        uses: sibiraj-s/action-eslint@v3
        with:
          eslint-args: "--ignore-path=.gitignore --quiet"
          extensions: "js,ts"
          annotations: true

  Tests:
    runs-on: ubuntu-latest
    needs: [CodeAnalysis]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('package-lock.json') }}

      - name: Run test
        run: npm run test:ci

  Coverage:
    runs-on: ubuntu-latest
    needs: [Tests]
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
